/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"
#include <time.h>

void *
initialize_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	return (void *) &result;
}

double *
get_next_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;
    double range = (1000 - 0);
    double div = RAND_MAX / range;
    srand(time(NULL));
    result += (rand() / div);
    printf("%f \n",result);
	return &result;
}
